AllCops:
  Exclude:
    - 'Gemfile'

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
  Max: 30

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 150